name: deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name : Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: |
            ls
            cd front_end
            npm install
            npm run build
    - name : transfert_files
      uses : appleboy/scp-action@v0.1.7
      with:
        host: ssh-alantuning.alwaysdata.net
        username: alantuning_secret
        password: saucisse
        source: "front_end/dist/"
        target: /home/alantuning
    
